name: Create test release
on:
  workflow_dispatch:
    inputs:
       version:
        description: "create a test version for primazctl use"
        required: true
        default: "latest"

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-20.04
    env:
      PRIMAZA_CONFIG_FILE: primaza_config_${{ github.event.inputs.version }}.yaml
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: get Kustomize and config
        run: make all

      - name: create single file config for version
        id: create_config
        run: |
          cd scripts/config/default
          ../../bin/kustomize edit set image controller=${{ github.event.inputs.version }}
          cd ../../..
          scripts/bin/kustomize build scripts/config/default > ${PRIMAZA_CONFIG_FILE}


      - name: Create the the release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          body: "Release for testing purposes only"
          files: ${{ env.PRIMAZA_CONFIG_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
